zyantific/zycore-c

include/Zycore/LibC.h
The compiler in question is MSVC, but it seems plausible that other compilers might do this as well. Basically I've been developing a UEFI driver that uses Zydis (with excellent results btw, if you'll take my word for it I can honestly say that I've abused Zydis in very many ways and haven't seen a single issue. So go add UEFI to the list of supported/tested platforms in the README already :wink:)
Today I hit this little snag:
```
EfiGuardDxe.lib(Utils.obj) : error LNK2001: unresolved external symbol memset
c:\dev\efi\workspace\Build\EfiGuard\RELEASE_VS2017\X64\EfiGuardPkg\EfiGuardDxe\EfiGuardDxe\DEBUG\EfiGuardDxe.dll : fatal error LNK1120: 1 unresolved externals
```
This is due to MSVC being clever (well OK... I'll admit it's pretty clever, but not helpful here) and wholesale replacing …
=> Prevent overly clever compiler optimizations #if ZYAN_NO_LIBC

include/Zycore/Defines.h, include/Zycore/Format.h
This adds two decorators named `ZYAN_PRINTF_ATTR` and `ZYAN_WPRINTF_ATTR`. The former is used to decorate `ZyanStringInsertFormat` and `ZyanStringAppendFormat` for type checking (GCC and Resharper) and syntax highlighting (Resharper) of varargs arguments.
=> Add ZYAN_PRINTF_ATTR and ZYAN_WPRINTF_ATTR

include/Zycore/API/Synchronization.h, include/Zycore/API/Thread.h, src/API/Terminal.c
MinGW is case sensitive when including files, and it ships the main Windows header as `windows.h`.
This patch converts every reference of the Windows header to lower case.
I ran tests on both MinGW and MSVC successfully.
I used MinGW version 9.2.0 and MSVC 2017 version 15.9.8, in a Windows 10 virtual machine.
Each compiler generated binaries targeting 32 and 64 bits platforms in Release mode.
=> Fix to allow compilation with MinGW

include/Zycore/Defines.h
Required for zydis and ultimately for Firefox.
=> Add support for Solaris OS

include/Zycore/Defines.h
Should fix Firefox build with GCC: https://bugzilla.mozilla.org/show_bug.cgi?id=1604740
=> Allow to build with C++ (_Static_assert not defined by C++)

examples/String.c, examples/Vector.c, include/Zycore/API/Memory.h, include/Zycore/API/Synchronization.h, include/Zycore/API/Terminal.h, include/Zycore/API/Thread.h, include/Zycore/Allocator.h, include/Zycore/ArgParse.h, include/Zycore/Bitset.h, include/Zycore/Comparison.h, include/Zycore/Defines.h, include/Zycore/Format.h, include/Zycore/LibC.h, include/Zycore/List.h, include/Zycore/Object.h, include/Zycore/Status.h, include/Zycore/String.h, include/Zycore/Types.h, include/Zycore/Vector.h, include/Zycore/Zycore.h, src/Bitset.c, src/Format.c, src/List.c, src/String.c, src/Vector.c
In private conversation it was decided that we want to switch away from the unnecessarily verbose explicit `@brief` doxygen syntax and instead use auto-brief.
This PR implements this change. All occurrences of `@brief` were replaced automatically and then, after review of the changes, indentation of the next line(s) were fixed manually.
Things to look out for in review:
- Incorrect indentation of the next line after line where `@brief` was removed
- Parameter documentations that were previously incorrectly created with `@brief` instead of `@param` and now don't have any directive at all
While at it, any trialing whitespace in files was stripped as well.
Priority is high because this will likely clash with any possible other PR and require ugly rebases.
=> Use auto-brief doxygen syntax

include/Zycore/Defines.h
Linux kernel 5.4, introduce a new fallthrough macro, which cause compilation failure of zycore-c.
(https://github.com/torvalds/linux/commit/294f69e662d1570703e9b56e95be37a9fd3afba5)
=> Replace fallthrough attribute to __fallthrough__

CMakeLists.txt, cmake/zycore-config.cmake.in
The current `config.cmake` file is almost empty and is installed in the wrong directory.
Also add the `config-version.cmake` file.
=> Fix cmake config files

CMakeLists.txt
Moved from: https://github.com/zyantific/zydis/pull/217
I had to adapt the code a bit for it to actually also affect Zydis when enabled (the old code would just affect the current makefile + all children, but not parents).
=> Add `ZYAN_FORCE_ASSERTS` CMake option

CMakeLists.txt, cmake/zyan-functions.cmake, cmake/zycore-config.cmake.in
Now when calling `find_package(Zycore)` users will be able to use the `zyan` functions.
This would make it possible to use `find_package(Zycore)` to find and use the system Zycore library in Zydis. Before this change, if instead of compiling Zycore with `add_subdirectory()` you used `find_package(Zycore)`, the build failed, because functions like `zyan_set_common_flags()` were not imported.
I also removed `ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}` etc from `install(TARGETS ...)` because they are already [set by default](https://cmake.org/cmake/help/latest/command/install.html#targets)
=> build(cmake): export and install zyan_* functions

CMakeLists.txt
The changes are not that big, but I decided to split them in multiple commits because every one of them does a different thing. They are all related though, so I prepared a single PR. Here's their description (from the commit messages):
This helps with automated testing, as tests can be ran with `ctest` or by "building" the target `test`
I also changed the way the C++ standard version is handled; the tests require C++17, and this was previously accomplished by manually passing the `-std=c++17` flag, while the "CMake way" of doing this is to set the `CXX_STANDARD` property. Unfortunately the value `17` of the property was only added in CMake 3.8, so when using older CMake versions the flag is still passed manually. I've also set the `CXX_EXTENSIONS` and `CXX_STANDARD_REQUIRED` to false and …
=> Tests tweaks

include/Zycore/Defines.h, src/Format.c
This PR does two things to add basic support for WebAssembly builds:
1. detect WebAssembly architecture (and WASI platform), and
2. invoke appropriate formatters for wasm, which is sort-of a 32-bit architecture
The motivation is to use Zydis in a library compiled to WebAssembly. I'm assuming `ZYAN_NO_LIBC` will be sufficient; therefore, I didn't implement any of the platform interfaces for WASI (such as sync, threading, or memory).
=> add basic WebAssembly support

CMakeLists.txt, include/Zycore/API/Memory.h, include/Zycore/API/Process.h, include/Zycore/API/Synchronization.h, include/Zycore/API/Terminal.h, include/Zycore/API/Thread.h, include/Zycore/Allocator.h, include/Zycore/Bitset.h, include/Zycore/Defines.h, include/Zycore/Format.h, include/Zycore/List.h, include/Zycore/String.h, include/Zycore/Vector.h, include/Zycore/Zycore.h
This PR gets rid of the CMake generated `ZycoreExportConfig.h` header. It's annoying to deal with in non-CMake environments because CMake generates it for one specific compiler (so you can't just generate it once and use it everywhere) and also doesn't really provide much that we couldn't just as well detect at compile time.
Because the previous exports created by CMake were rather cryptic, I also took the opportunity to rename them:
- `ZYCORE_STATIC_DEFINE` -> `ZYCORE_STATIC_BUILD`
- `Zycore_EXPORTS` -> `ZYCORE_SHOULD_EXPORT`
There was a third define that we manually defined previously, `ZYCORE_EXPORTS` (mind the casing), which was seemingly unused, so I removed it.
Because we don't have CI here, I created a branch in the Zydis repo and updated the submodule. Builds just fine, results …
=> Get rid of CMake export headers

cmake/zyan-functions.cmake
Upcoming changes in Zydis (use of anonymous unions) require C11. With the standard now being 11 years old, we decided (in direct communication) that it is probably acceptable to bump our requirements here.
=> Switch minimum supported C standard to C11

cmake/zyan-functions.cmake
Turns out that the Windows world is not quite ready for C11 yet.
=> Don't enable C11 for MSVC

CMakeLists.txt
This patch adds a doc target generating Doxygen documentation; please see the individual commits for details :)
=> build: add doc target

CMakeLists.txt
Both the documentation target in zycore and zydis were previously called "doc" which caused a CMake error in zydis complaining about the same name being used twice.
```
CMake Error at /usr/share/cmake/Modules/FindDoxygen.cmake:1165 (add_custom_target):
add_custom_target cannot create target "doc" because another target with
the same name already exists.  The existing target is a custom target
created in source directory "/home/ath/devel/zydis/dependencies/zycore".
See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
CMakeLists.txt:460 (doxygen_add_docs)
```
CC @Tachi107
=> CMake: rename target `doc` -> `ZycoreDoc`

src/API/Process.c
The `ifdef` in `Process.c` previously didn't include the header selection, resulting in "Unsupported platform detected" on non-Windows/non-Unix platforms like Emscripten.
=> Fix no-libc build on "other" platforms

include/Zycore/Defines.h, include/Zycore/Types.h
Hi,
These two commits improve support for building Zydis for the linux kernel in a couple of corner cases:
The first commit introduces the ZYAN_DIV64 macro to fix a failure when linking Zydis on a 32bit linux kernel. The Zydis changes will be submitted in a separate PR.
The second PR adds support for building Zydis in NO_LIBC mode with old versions of GCC.
Thanks,
=> Better support for linux kernel

include/Zycore/API/Memory.h, src/API/Memory.c
Multiple functions without arguments were missing the `(void)` that prevents them from being interpreted as not having a prototype. Newer Clang versions started printing warnings for that in pedantic mode.
Will send similar PR for Zydis once this is merged.
=> Add missing `(void)` on functions without args

CMakeLists.txt, include/Zycore/Zycore.h, resources/VersionInfo.rc
Cut a new release of Zycore to be used in Zydis v4.1 release.
Commits included: https://github.com/zyantific/zycore-c/compare/v1.4.1...master
Going with v1.5.0 (instead of v1.4.1) because the `ZYAN_GETENV` macro that we added is needed by Zycore, so distro maintainers will have to update Zycore first.
=> Bump version to v1.5.0

resources/VersionInfo.rc
If `llvm-rc` is used as the resource compiler, the following error occurs if `ZYCORE_BUILD_SHARED_LIB` is enabled:
```
llvm-rc: Error in VERSIONINFO statement (ID 1):
Non-ASCII 8-bit codepoint (∩┐╜) can't be interpreted in the current codepage
```
This is a common issue encountered with `llvm-rc`, see curl/curl#7765.
Following the workaround from  `libcurl`, this pull request changes the copyright symbol `©` to `(C)`.
=> Fix issue with `llvm-rc` when `ZYCORE_BUILD_SHARED_LIB` is enabled

CMakeLists.txt
To offer the same public target regardless of zycore-c is used as a subproject or via `find_package`.
This should be complemented by Zydis linking "Zycore::Zycore".
(Noticed in reviewing a vcpkg port update.)
=> Add alias target "Zycore::Zycore"

.github/workflows/main.yml, CMakeLists.txt, include/Zycore/Zycore.h, meson.build, resources/VersionInfo.rc
Required by https://github.com/zyantific/zydis/pull/546#issuecomment-2579264830
=> Bump version to v1.5.1

include/Zycore/Defines.h
=> Add __attribute__((unused)) to ZYAN_STATIC_ASSERT

CMakeLists.txt, include/Zycore/Defines.h, meson.build
=> build: support gnu symbol visibility when building DSO

CMakeLists.txt, include/Zycore/Zycore.h, meson.build, resources/VersionInfo.rc
Create another Zycore release including a bunch of the recent fix-ups in prep for [the Zydis 4.1.1 release](https://github.com/zyantific/zydis/pull/547).
CC @mochaaP
=> Bump version to `v1.5.2`

CMakeLists.txt, CMakeLists.txt.in
This PR fixes build errors on newer versions of CMake. Since [version 3.10 was released in 2018](https://github.com/Kitware/CMake/releases/tag/v3.10.0), it makes sense to update to the min version.
<details>
<summary>build errors (click to expand)</summary>
```
$ cmake --version
cmake version 4.0.1
$ mkdir -p build && cd build
$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C …
```
=> chore: bump min cmake version to 3.10, update googletest

include/Zycore/Defines.h, src/Format.c
PR to address problem brought up in https://github.com/zyantific/zycore-c/pull/87#issuecomment-2889189580 and https://github.com/zyantific/zydis/pull/572.
`ZYAN_ARCHITECTURE_WIDTH` is hardcoded for well-known architectures. For others `__LP64__` check is performed on a best effort basis. Generally it should be reliable and it seems to be widely used.
Conditions in `src/Format.c` are now inverses of each other to avoid desync issues (like in https://github.com/zyantific/zydis/pull/572).
=> Added `ZYAN_ARCHITECTURE_WIDTH`
